### ISSUE TITLE
Feature Request : Support casting of YouTube Shorts links

### ISSUE THREAD

**Issue by maniaxuk** [WPettersson/firefox-send-to-xbmc#2]
Hi

First off thanks for the work that's been done from the original project to add new supported video services (iPlayer especially) and to keep other services working

I make a lot of use of the add-on in Firefox to send YouTube links to my Kodi box which works perfectly but YouTube now has a different URL structure for their YouTube Shorts service which the add-on doesn't understand

I currently get around the problem by having another addon ([Redirect YouTube Shorts to YouTube](https://addons.mozilla.org/en-GB/firefox/addon/redirect-shorts-to-youtube/)) that rewrites the Shorts links to a standard YouTube link which I can then send to Kodi but it would be nice to be able to send the (rewritten) shorts link directly to Kodi thereby bypassing the additional step currently needed

Regards

-maniaxuk-

**Comment by WPettersson** [comment]
I think I've fixed that in the linked commit, and bumped the version. I now have to figure my way around Mozilla's packaging system, which from the looks of it is going to be harder than making the actual change.

**Comment by WPettersson** [comment]
Okay, think I worked out the packing thing, AMO should update soon.

**Comment by maniaxuk** [comment]
Just updated my Firefox install to 3.1.5 of the add-on and it all seems to be working perfectly

Thank you for the amazingly speedy update :)
